### ISSUE TITLE
Preview SVG image has been broken

### ISSUE THREAD

**Issue by samchon** [moltar/typescript-runtime-type-benchmarks#1082]
https://raw.githubusercontent.com/moltar/typescript-runtime-type-benchmarks/master/docs/results/preview.svg

**Comment by samchon** [comment]
![Screenshot_20230620_000022_Chrome](https://github.com/moltar/typescript-runtime-type-benchmarks/assets/13158709/01fc59f0-c3a6-47b3-8fe5-cecf3fd38ad0)

Like this

**Comment by moltar** [comment]
Ah, you are right. I didn't even notice the top-right graph missing. Was so focused on thinking that the file was corrupt.

@hoeck Any ideas?

**Comment by hoeck** [comment]
Seems to be because of a vega-lite major version upgrade: https://github.com/moltar/typescript-runtime-type-benchmarks/commit/ab324e2006ebaa74186ffabfb000924ba4da494d#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R76

I'll see if I can find a quick way to get that preview work with the new version.

**Comment by samchon** [comment]
@hoeck Wow, you've commented at the same time. 

@moltar - If @hoeck founds better way, please discard my PR.

**Comment by hoeck** [comment]
> @hoeck Wow, you've commented at the same time.
:grin: 

> @moltar - If @hoeck founds better way, please discard my PR.
nah, to be honest with you, I don't like having stuff break by updating dependencies.

BUT **huuuuge BUT** it needs to be done. Otherwise it will get harder and harder and finally next to impossible to update anything.

And in this case, it seems the preview generation is broken because the way I generate the data that is passed to vega-lite. Looks like that only worked because of some undocumented internal behavior in versions before 5.

**Comment by samchon** [comment]
@moltar @hoeck Components are not sorted by rank (or graph is mis-drawn?).

![image](https://github.com/moltar/typescript-runtime-type-benchmarks/assets/13158709/3564641d-8bce-4461-a8a2-2f4ea5c6fa29)

**Comment by hoeck** [comment]
> Components are not sorted by rank (or graph is mis-drawn?).

@samchon right, unfortunately that is a limitation of the "repeated bar graph" of vega-lite that I am (ab)using here.

Vega-lite expects that each single bar graph contains the same libraries - but I want only the fastest 3 so each chart contains a different set. Applying sorting will cause each library to appear in every chart.

An alternative would be to generate a different chart (e.g. a combined bar chart) or to create 4 separate preview SVGs (one for each benchmark) to include in the readme.
Maybe the latter wouldn't look too bad when it's made in the format of a banner.

**Comment by samchon** [comment]
May I try `d3` like below? I can have a time at July.

https://github.com/samchon/typia/tree/master/benchmark/results/11th%20Gen%20Intel(R)%20Core(TM)%20i5-1135G7%20%40%202.40GHz
