### ISSUE TITLE
Add `to-typed`

### ISSUE THREAD

**Issue by moltar** [moltar/typescript-runtime-type-benchmarks#897]
https://github.com/jsoldi/to-typed

@jsoldi? 😁

**Comment by jsoldi** [comment]
Happy to help with this but I haven't figured out how to work with this library. I downloaded the package and tried to add a dummy case in the cases folder by cloning one of the existing ones. I also added it to `cases/index.ts` and did `npm run test`, `npm run docs:build` and `npm run docs:start` but keep seeing the old cases only. Did I miss any step?

**Comment by hoeck** [comment]
@jsoldi looks like you forgot to run the actual benchmarks with `npm run start`? That will run all cases, write the results to `docs/results`, which is then shown in the docs ui.

For development, you can also choose which cases are benchmarked by using `npm run start run <your-package-name> <another-package-name>`.

Also, for your cases to be picked up by the tests you'll need to manually import it here: https://github.com/moltar/typescript-runtime-type-benchmarks/blob/master/test/benchmarks.test.ts

**Comment by jsoldi** [comment]
So it seems that the problem was that I'm on Windows, which doesn't support the shebang code on top of ts-node's `bin.js` file. I guess this also explains why this file was randomly opening on my text editor. The way I solved it was by changing [this line](https://github.com/moltar/typescript-runtime-type-benchmarks/blob/929a5d0bb5d3a85dd7522983c2ce91d9bf208d0f/index.ts#L30) to this:

```typescript
const cmd = ['node', ...process.argv.slice(0, 2), 'run-internal', c];
```

But I'm not sure if that'll work the same on Linux although I think it should. 

Anyway, I just sent pull request https://github.com/moltar/typescript-runtime-type-benchmarks/pull/902 with the new `to-typed` case. I didn't include the change above since that's a separate issue, but feel free to use that code if it work's on Linux too.

**Comment by moltar** [comment]
@jsoldi ah, thanks for that. Good to know! Will move that into an issue.

**Comment by DarkGL** [comment]
Can we close it as https://github.com/moltar/typescript-runtime-type-benchmarks/pull/902 is already merged?
